In [75]:
import numpy as np
import scipy
import random
import networkx as nx
import string

In [101]:
pip install lk_heuristic

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 42.9 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.13.1
    Uninstalling plotly-5.13.1:
      Successfully uninstalled plotly-5.13.1


In [23]:
pip install resample

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [55]:
pip install networkx

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [80]:
!sudo apt-get install python3-dev graphviz libgraphviz-dev pkg-config

Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu4).
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-dev set to manually installed.
graphviz is already the newest version (2.42.2-3build2).
The following additional packages will be installed:
  libgail-common libgail18 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common
  libgvc6-plugins-gtk libxdot4
Suggested packages:
  gvfs
The following NEW packages will be installed:
  libgail-common libgail18 libgraphviz-dev libgtk2.0-0 libgtk2.0-bin
  libgtk2.0-common libgvc6-plugins-gtk libxdot4
0 upgraded, 8 newly installed, 0 to remove and 24 not upgraded.
Need to get 2,148 kB of archives.
After this operation, 7,427 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libgtk2.0-common all 2.24.32-4ubuntu4 [126 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libgtk2.0-0 amd64

In [81]:
pip install pygraphviz

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached pygraphviz-1.10.zip (120 kB)
  Preparing metadata (setup.py) ... done
  Created wheel for pygraphviz: filename=pygraphviz-1.10-cp39-cp39-linux_x86_64.whl size=183754 sha256=99d20f32ae0ad64e0f6b5bf893676a72515a89bead0da85ff3daa4a58ef656a8
  Stored in directory: /root/.cache/pip/wheels/fc/2a/e8/14a3ad923e265b2c264a2810d1ae36769ce99421c5dce75312
Successfully built pygraphviz


In [57]:
poisson_options = np.random.poisson(1.3825, 52)
poisson_options
# 0, 1, 2

array([1, 2, 4, 2, 3, 0, 1, 0, 2, 2, 1, 0, 1, 1, 2, 1, 2, 3, 1, 1, 1, 2,
       3, 1, 2, 1, 3, 0, 1, 1, 4, 0, 4, 1, 1, 1, 1, 3, 3, 0, 1, 1, 1, 1,
       0, 3, 1, 3, 2, 1, 1, 1])

In [64]:
poisson_options = np.random.poisson(1.3825, )
poisson_options
# 0, 1, 2

array([0, 2, 2, 2])

In [58]:
picked = random.sample(sorted(poisson_options), 3)
# 0, 1, 2
picked

[1, 1, 3]

In [52]:
def half_time_array(oldImage, lambda):
    newImage=(oldImage/2)
    newImage = np.random.poisson(newImage, lam = lambda)
    return newImage

SyntaxError: ignored

In [49]:
half_time_array(poisson_options)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0])

In [54]:
np.random.poisson(lam = 1.5, [1,2,3])

SyntaxError: ignored

In [56]:
dt = [('len', float)]
dt

[('len', float)]

In [86]:
A = np.array([(0, 4, 0),
             (0, 0, 7),
             (2, 0, 0)])

A = A.view(dt)

A

array([[(0.0e+000,), (2.0e-323,), (0.0e+000,)],
       [(0.0e+000,), (0.0e+000,), (3.5e-323,)],
       [(9.9e-324,), (0.0e+000,), (0.0e+000,)]], dtype=[('len', '<f8')])

In [96]:
# G = nx.from_numpy_matrix(A)
G = nx.DiGraph(np.array(A))
G = nx.relabel_nodes(G, dict(zip(range(len(G.nodes())), string.ascii_uppercase)))

G = nx.drawing.nx_agraph.to_agraph(G)

G.node_attr.update(color = "red", style = "filled")
G.edge_attr.update(color = "blue", width = 0.2)

G.draw('/tmp/out.png', format = 'png', prog = 'neato')

In [98]:
# B = np.array([(0, 0, 4),
#              (7, 0, 0),
#              (0, 2, 0)])

B = np.array([
        [0, 2451, 713, 1018, 1631, 1374, 2408, 213, 2571, 875, 1420, 2145, 1972],
        [2451, 0, 1745, 1524, 831, 1240, 959, 2596, 403, 1589, 1374, 357, 579],
        [713, 1745, 0, 355, 920, 803, 1737, 851, 1858, 262, 940, 1453, 1260],
        [1018, 1524, 355, 0, 700, 862, 1395, 1123, 1584, 466, 1056, 1280, 987],
        [1631, 831, 920, 700, 0, 663, 1021, 1769, 949, 796, 879, 586, 371],
        [1374, 1240, 803, 862, 663, 0, 1681, 1551, 1765, 547, 225, 887, 999],
        [2408, 959, 1737, 1395, 1021, 1681, 0, 2493, 678, 1724, 1891, 1114, 701],
        [213, 2596, 851, 1123, 1769, 1551, 2493, 0, 2699, 1038, 1605, 2300, 2099],
        [2571, 403, 1858, 1584, 949, 1765, 678, 2699, 0, 1744, 1645, 653, 600],
        [875, 1589, 262, 466, 796, 547, 1724, 1038, 1744, 0, 679, 1272, 1162],
        [1420, 1374, 940, 1056, 879, 225, 1891, 1605, 1645, 679, 0, 1017, 1200],
        [2145, 357, 1453, 1280, 586, 887, 1114, 2300, 653, 1272, 1017, 0, 504],
        [1972, 579, 1260, 987, 371, 999, 701, 2099, 600, 1162, 1200, 504, 0],
    ])

B = B.view(dt)

In [ ]:
center_node = 5  # Or any other node to be in the center
edge_nodes = set(G) - {center_node}
# Ensures the nodes around the circle are evenly distributed
pos = nx.circular_layout(G.subgraph(edge_nodes))
pos[center_node] = np.array([0, 0])  # manually specify node position

array([[   0, 2451,  713, 1018, 1631, 1374, 2408,  213, 2571,  875, 1420,
        2145, 1972],
       [2451,    0, 1745, 1524,  831, 1240,  959, 2596,  403, 1589, 1374,
         357,  579],
       [ 713, 1745,    0,  355,  920,  803, 1737,  851, 1858,  262,  940,
        1453, 1260],
       [1018, 1524,  355,    0,  700,  862, 1395, 1123, 1584,  466, 1056,
        1280,  987],
       [1631,  831,  920,  700,    0,  663, 1021, 1769,  949,  796,  879,
         586,  371],
       [1374, 1240,  803,  862,  663,    0, 1681, 1551, 1765,  547,  225,
         887,  999],
       [2408,  959, 1737, 1395, 1021, 1681,    0, 2493,  678, 1724, 1891,
        1114,  701],
       [ 213, 2596,  851, 1123, 1769, 1551, 2493,    0, 2699, 1038, 1605,
        2300, 2099],
       [2571,  403, 1858, 1584,  949, 1765,  678, 2699,    0, 1744, 1645,
         653,  600],
       [ 875, 1589,  262,  466,  796,  547, 1724, 1038, 1744,    0,  679,
        1272, 1162],
       [1420, 1374,  940, 1056,  879,  225, 1891, 

In [97]:
# G = nx.from_numpy_matrix(A)
G = nx.DiGraph(np.array(B))

# center_node = 0  # Or any other node to be in the center
# edge_nodes = set(G) - {center_node}
# # Ensures the nodes around the circle are evenly distributed
# pos = nx.circular_layout(G.subgraph(edge_nodes))
# pos[center_node] = np.array([0, 0])  # manually specify node position

G = nx.relabel_nodes(G, dict(zip(range(len(G.nodes())), string.ascii_uppercase)))

G = nx.drawing.nx_agraph.to_agraph(G)

# G.node_attr.update(color = "red", style = "filled")
# G.edge_attr.update(color = "blue", width = 2.0)

G.draw('/tmp/out_2.png', format = 'png', prog = 'neato')

/usr/local/lib/python3.9/dist-packages/pygraphviz/agraph.py:1405: RuntimeWarning: Warning: bad edge len "1.211e-320" in  - setting to 1.00

  warnings.warn(b"".join(errors).decode(self.encoding), RuntimeWarning)
